### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by XVilka** [charlesvdv/nom-bibtex#3]
There is a [discussion](https://github.com/latex-lsp/texlab/issues/87) in [texlab](https://texlab.netlify.com/) about dropping the [citeproc-js](https://github.com/Juris-M/citeproc-js) in favor of the Rust-based solution, and nom-bibtex was mentioned there. So I am curious about the state of the project and things missing.

**Comment by charlesvdv** [comment]
Hello @XVilka! 

Thanks for considering `nom-bibtex` for your project! 
To be honest, the project was mostly to familiarise myself with `nom` and `rust`. I will gladly accept any pull requests that improve the lib but I don't think I will devote a lot of my time to fix bugs.
I also tried to follow as closely as possible the [spec](http://www.bibtex.org/Format/) but I'm not 100% sure it follows all the edge cases. You might want to test with a few of your tests containing bibtex just to be sure it will fit your need.

**Comment by charlesvdv** [comment]
@XVilka I will close the issue as it appears the discussion on `texlab` is closed.
